[project]
name = "spdx-storage"
version = "0.1.0"
description = "Storage for SPDX data"
readme = "README.md"
authors = [
    { name = "Alexios Zavras", email = "spdx@zvr.gr" }
]
requires-python = ">=3.14"
dependencies = [
    "platformdirs>=3.0.0",
    "rdflib>=7.6.0",
    "triplestore",
]

[project.scripts]
spdx-storage = "spdx_storage.cli:main"

[build-system]
requires = ["uv_build>=0.11.24,<0.12.0"]
build-backend = "uv_build"


[tool.ruff]
exclude = [ ".git", ".ruff_cache", ".venv", ".vs", ".vscode", ]
fix = false
indent-width = 4
line-length = 120
# output-format = "full"
output-format = "grouped"
preview = true
required-version = ">=0.15"
show-fixes = true
target-version = "py314"

[tool.ruff.analyze]
direction = "dependencies"
preview = true

[tool.ruff.format]
docstring-code-format = true
indent-style = "space"
line-ending = "native"
nested-string-quote-style = "alternating"
preview = true
quote-style = "double"
skip-magic-trailing-comma = true

[tool.ruff.lint]
fixable = ["ALL"]
future-annotations = true
ignore = [ "AIR", "ANN", "missing-trailing-comma", "D", "DJ", "DOC", "FAST", "NPY", "PD", ]
logger-objects = []
preview = true
select =  ["ALL"]
unfixable = []

[tool.ruff.lint.per-file-ignores]

[tool.ruff.lint.isort]
case-sensitive = true
lines-between-types = 0
split-on-trailing-comma = false

[tool.ruff.lint.mccabe]
max-complexity = 12

[dependency-groups]
dev = [
    "pytest>=9.1.1",
    "triplestore[all]>=0.1.1",
]

